### ISSUE TITLE
Interstitial ads wont show until I make it show when interacting with an UI object

### ISSUE THREAD

**Issue by ablohme86** [marcojak/MTAdmob#115]
I want to show an interstitial ads on startup, however it just fails, but if I call the code below again from a button, it will show up.
The way I start it is when a ContentPage is constructed

CrossMTAdmob.Current.LoadInterstitial(Globals.InterstitialAdsID_iOS);
CrossMTAdmob.Current.ShowInterstitial();

**Comment by marcojak** [comment]
The reason why it doesn't work is that you don't give time to the app to load the ads.
When you call ShowInterstitial, the interstitial still has to be loaded.
Before calling ShowInterstitial you need to check if the interstitial is actually loaded.

I'm working on a new version that I hope to release in the next couple of days and I think I'll add an async method and a normal one with callback so that people can chose what they prefer.

**Comment by ablohme86** [comment]
Aha, so, just await for LoadInterstitial? And then hit ShowInterstitial when the event calls for it? Thats the best way to show interstitials on startup of an app?

**Comment by ablohme86** [comment]
Yes, that solved the issue thank you
